const BADGE_CLASS: Record<string, string> = {
  Workshop: 'b-workshop',
  'After Dark': 'b-afterdark',
  'Happy Hour': 'b-happyhour',
  'Day Party': 'b-party',
  Brunch: 'b-brunch',
  Ball: 'b-ball',
  Outdoors: 'b-outdoors',
  Meetup: 'b-meetup',
  Cultural: 'b-cultural',
  Wellness: 'b-wellness',
  Free: 'b-free',
  Black: 'b-cultural',
  'Black-owned': 'b-cultural',
  Sapphic: 'b-party',
  Lesbian: 'b-party',
  WLW: 'b-party',
  'Woman-owned': 'b-brunch',
  'Trans/GNC': 'b-workshop',
  Trans: 'b-workshop',
  GNC: 'b-workshop',
  Nonbinary: 'b-workshop',
  FLINTA: 'b-workshop',
  POC: 'b-meetup',
  Queer: 'b-afterdark',
  'Queer-friendly': 'b-happyhour',
  MLM: 'b-ball',
  Drag: 'b-ball',
  '30+': 'b-outdoors',
  ENM: 'b-brunch',
  Kink: 'b-afterdark',
  Masc: 'b-meetup',
  'Youth/Family': 'b-wellness',
  Hotel: 'b-meetup',
  Eat: 'b-brunch',
  Drink: 'b-happyhour',
  Dance: 'b-party',
  Experience: 'b-cultural',
};

export function badgeClassForLabel(label: string): string {
  return BADGE_CLASS[label] ?? 'b-workshop';
}
