/* eslint-disable */
// Auto-generated by scripts/sync-events.ts from the Google Sheets Sept_Events tab. Do not edit by hand.
import type { PrideEvent } from '../../types/event';

export const generatedEvents: PrideEvent[] = [
  {
    "id": "september-events-2",
    "festival": "september-events",
    "day": "friday",
    "dayDate": "2026-09-04",
    "dayLabel": "Friday",
    "name": "STAMINA: LIME — The Arrival (Reggae & Wine Social)",
    "organizer": "Out N Bad (STAMINA Festival)",
    "types": [
      "live-show"
    ],
    "vibesRaw": "creative community live show",
    "free": true,
    "price": "Free",
    "badges": [
      "Live Show",
      "Free"
    ],
    "time": "7:00 PM",
    "location": "Saint James Libations · 269 Stanhope Street, Brooklyn, NY 11237",
    "vibeTags": [
      "Creative",
      "Community",
      "Live Show"
    ],
    "ctaHref": "https://www.eventbrite.com/e/stamina-lime-reggae-wine-social-queer-caribbean-festival-tickets-1990539477160",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-live-show",
    "city": "nyc",
    "prideSeries": "STAMINA 2026: Queer Caribbean Festival"
  },
  {
    "id": "september-events-3",
    "festival": "september-events",
    "day": "saturday",
    "dayDate": "2026-09-05",
    "dayLabel": "Saturday",
    "name": "STAMINA: DRIFT — The Tides of Poseidon (90s & 2000s Boat Party)",
    "organizer": "Out N Bad (STAMINA Festival)",
    "types": [
      "live-show"
    ],
    "vibesRaw": "creative community live show",
    "free": false,
    "price": "$40.00",
    "badges": [
      "Live Show"
    ],
    "time": "1:00 PM",
    "location": "CABANA at Skyport Marina · 2430 FDR Drive, New York, NY 10010",
    "vibeTags": [
      "Creative",
      "Community",
      "Live Show"
    ],
    "ctaHref": "https://www.eventbrite.com/e/stamina-drift-90s-2000s-boat-party-queer-caribbean-festival-tickets-1990692889019",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-live-show",
    "city": "nyc",
    "prideSeries": "STAMINA 2026: Queer Caribbean Festival"
  },
  {
    "id": "september-events-4",
    "festival": "september-events",
    "day": "saturday",
    "dayDate": "2026-09-05",
    "dayLabel": "Saturday",
    "name": "STAMINA: BLACKOUT — The House of Cleopatra (All Black & Gold Bashment Gala)",
    "organizer": "Out N Bad (STAMINA Festival)",
    "types": [
      "live-show"
    ],
    "vibesRaw": "creative community live show",
    "free": false,
    "price": "$30.00",
    "badges": [
      "Live Show"
    ],
    "time": "11:00 PM",
    "location": "littlefield · 635 Sackett Street, Brooklyn, NY 11217",
    "vibeTags": [
      "Creative",
      "Community",
      "Live Show"
    ],
    "ctaHref": "https://www.eventbrite.com/e/stamina-blackout-black-gold-bashment-gala-queer-festival-littlefield-tickets-1990810149749",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-live-show",
    "city": "nyc",
    "prideSeries": "STAMINA 2026: Queer Caribbean Festival"
  },
  {
    "id": "september-events-5",
    "festival": "september-events",
    "day": "sunday",
    "dayDate": "2026-09-06",
    "dayLabel": "Sunday",
    "name": "STAMINA: COLORS — The Rebellion of Athena (Paint & Powder Fete)",
    "organizer": "Out N Bad (STAMINA Festival)",
    "types": [
      "live-show"
    ],
    "vibesRaw": "creative community live show",
    "free": false,
    "price": "$30.00",
    "badges": [
      "Live Show"
    ],
    "time": "3:00 PM",
    "location": "Parklife · 636 Degraw Street, Brooklyn, NY 11217",
    "vibeTags": [
      "Creative",
      "Community",
      "Live Show"
    ],
    "ctaHref": "https://www.eventbrite.com/e/stamina-colors-paint-powder-fete-queer-caribbean-festival-parklife-tickets-1990813310202",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-live-show",
    "city": "nyc",
    "prideSeries": "STAMINA 2026: Queer Caribbean Festival"
  },
  {
    "id": "september-events-7",
    "festival": "september-events",
    "day": "tuesday",
    "dayDate": "2026-09-08",
    "dayLabel": "Tuesday",
    "name": "Trans Figure Drawing at The Bush",
    "organizer": "The Bush",
    "types": [
      "live-show"
    ],
    "vibesRaw": "creative community live show",
    "free": false,
    "badges": [
      "Live Show"
    ],
    "time": "Verify manually",
    "location": "The Bush · 333 Troutman St, #Store 4, Brooklyn, NY 11237",
    "vibeTags": [
      "Creative",
      "Community",
      "Live Show"
    ],
    "ctaHref": "https://www.eventbrite.com/e/trans-figure-drawing-at-the-bush-tickets-1986346596140?aff=oddtdtcreator",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-live-show",
    "city": "nyc"
  },
  {
    "id": "september-events-17",
    "festival": "september-events",
    "day": "saturday",
    "dayDate": "2026-08-29",
    "dayLabel": "Saturday",
    "name": "Something Lit For The Ladies: Countdown To Atlanta Black Pride",
    "organizer": "🚺 Xxclusive Vibes 🚺",
    "types": [
      "live-show"
    ],
    "vibesRaw": "creative community live show",
    "free": false,
    "badges": [
      "Live Show"
    ],
    "time": "",
    "location": "ATL",
    "vibeTags": [
      "Creative",
      "Community",
      "Live Show"
    ],
    "ctaHref": "https://posh.vip/e/something-lit-for-the-ladies-2026-8-30-7-0?t=series",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-live-show",
    "city": "atlanta",
    "prideSeries": "ATL Black Pride"
  },
  {
    "id": "september-events-18",
    "festival": "september-events",
    "day": "wednesday",
    "dayDate": "2026-09-02",
    "dayLabel": "Wednesday",
    "name": "ATLANTA BLACK PRIDE 2026: 20 YEAR ANNIVERSARY - ALL ACCESS PASS",
    "organizer": "PURE ENHERGY x SHEFEST",
    "types": [],
    "vibesRaw": "",
    "free": false,
    "price": "$221.00",
    "badges": [],
    "time": "5:00 PM",
    "location": "Atlanta, GA, USA",
    "vibeTags": [],
    "ctaHref": "https://posh.vip/e/atlanta-black-pride-2026-20-year-anniversary-1",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-day-party",
    "city": "atlanta"
  },
  {
    "id": "september-events-19",
    "festival": "september-events",
    "day": "wednesday",
    "dayDate": "2026-09-02",
    "dayLabel": "Wednesday",
    "name": "ATLANTA BLACK PRIDE: ROLL CALL SKATE PARTY",
    "organizer": "PURE ENHERGY x SHEFEST",
    "types": [],
    "vibesRaw": "",
    "free": false,
    "price": "$23.00",
    "badges": [],
    "time": "8:00 PM",
    "location": "SKATE TOWNE · 5570 Old National Hwy, Atlanta, GA 30349, USA",
    "vibeTags": [],
    "ctaHref": "https://posh.vip/e/roll-call-skate-party",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-day-party",
    "city": "atlanta"
  },
  {
    "id": "september-events-20",
    "festival": "september-events",
    "day": "thursday",
    "dayDate": "2026-09-03",
    "dayLabel": "Thursday",
    "name": "ATLANTA BLACK PRIDE: WELCOME TO ATLANTA: OFFICIAL KICKOFF PARTY",
    "organizer": "PURE ENHERGY x SHEFEST",
    "types": [],
    "vibesRaw": "",
    "free": false,
    "price": "$23.00",
    "badges": [],
    "time": "9:00 PM",
    "location": "MSR My Sister's Room · 1104 Crescent Ave NE, Atlanta, GA 30309, USA",
    "vibeTags": [],
    "ctaHref": "https://posh.vip/e/welcome-to-atlanta-official-kickoff-party",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-day-party",
    "city": "atlanta"
  },
  {
    "id": "september-events-21",
    "festival": "september-events",
    "day": "friday",
    "dayDate": "2026-09-04",
    "dayLabel": "Friday",
    "name": "ATLANTA BLACK PRIDE: BODY LANGUAGE: STRIPHER DAY PARTY",
    "organizer": "PURE ENHERGY x SHEFEST",
    "types": [],
    "vibesRaw": "",
    "free": false,
    "price": "$29.00",
    "badges": [],
    "time": "3:00 PM",
    "location": "Magic City · 241 Forsyth St SW, Atlanta, GA 30303, USA",
    "vibeTags": [],
    "ctaHref": "https://posh.vip/e/body-language-stripher-day-party",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-day-party",
    "city": "atlanta"
  },
  {
    "id": "september-events-22",
    "festival": "september-events",
    "day": "friday",
    "dayDate": "2026-09-04",
    "dayLabel": "Friday",
    "name": "ATLANTA BLACK PRIDE: FRIDAY NIGHT LIGHTS",
    "organizer": "PURE ENHERGY x SHEFEST",
    "types": [],
    "vibesRaw": "",
    "free": false,
    "price": "$45.00",
    "badges": [],
    "time": "10:00 PM",
    "location": "Cover · 4110 Memorial Dr Ste A, Decatur, GA 30032",
    "vibeTags": [],
    "ctaHref": "https://posh.vip/e/friday-night-lights-425",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-day-party"
  },
  {
    "id": "september-events-23",
    "festival": "september-events",
    "day": "saturday",
    "dayDate": "2026-09-05",
    "dayLabel": "Saturday",
    "name": "ATLANTA BLACK PRIDE: WETHER DAY PARTY",
    "organizer": "PURE ENHERGY x SHEFEST",
    "types": [],
    "vibesRaw": "",
    "free": false,
    "price": "$34.00",
    "badges": [],
    "time": "3:00 PM",
    "location": "Believe Music Hall · 181 Ralph David Abernathy Blvd SW, Atlanta, GA 30312",
    "vibeTags": [],
    "ctaHref": "https://posh.vip/e/atlanta-black-pride-wether-day-party",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-day-party"
  },
  {
    "id": "september-events-24",
    "festival": "september-events",
    "day": "saturday",
    "dayDate": "2026-09-05",
    "dayLabel": "Saturday",
    "name": "ATLANTA BLACK PRIDE: THE BLUEPRINT",
    "organizer": "PURE ENHERGY x SHEFEST",
    "types": [],
    "vibesRaw": "",
    "free": false,
    "price": "$50.00",
    "badges": [],
    "time": "10:00 PM",
    "location": "4 ELEMENTS {Formally SUITE LOUNGE} · 375 Luckie St NW, Atlanta, GA 30313",
    "vibeTags": [],
    "ctaHref": "https://posh.vip/e/atlanta-black-pride-the-blueprint",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-day-party"
  }
];
