/* eslint-disable */
// Auto-generated by scripts/sync-hospitality.mjs from the Google Sheets City_Hospitality_Tourism_Sept tab. Do not edit by hand.
import type { HospitalityItem } from '../types/hospitality';

export const generatedHospitalityItems: HospitalityItem[] = [
  {
    "id": "hospitality-hotel-mademoiselle-1",
    "city": "Paris",
    "business": "Hôtel Mademoiselle",
    "venueType": "Hotel",
    "uiCategory": "Where to Stay",
    "audienceTags": [
      "Queer-friendly"
    ],
    "description": "Paris hotel offering a dedicated TMP Community Perk for travelers who book directly.",
    "venueName": "Hôtel Mademoiselle",
    "venueAddress": "7, rue des Petits Hôtels\n75010 Paris – France",
    "price": "$$$",
    "hasCommunityPerk": true,
    "code": "MADE10",
    "bookingLink": "https://hotel-mademoiselle-paris.com/en/",
    "prideSeries": "GBP-associated / traveler-relevant, not an official GBP partnership"
  },
  {
    "id": "hospitality-okko-hotels-paris-gare-de-lest-2",
    "city": "Paris",
    "business": "OKKO Hotels Paris Gare de lEst",
    "venueType": "Hotel",
    "uiCategory": "Where to Stay",
    "audienceTags": [
      "Queer-friendly"
    ],
    "description": "Official Global Black Pride host hotel offering convenient accommodations for attendees traveling to Paris for Pride week.",
    "venueName": "OKKO Hotels Paris Gare de lEst",
    "venueAddress": "30 a Rue D'alsace, Paris, 75010 France",
    "price": "$$",
    "hasCommunityPerk": false,
    "code": "",
    "bookingLink": "https://globalblackpride.hotelplanner.com/Hotel/HotelRoomTypes.htm?hotelId=3781764&idTypeId=0&inDate=09/10/26&outDate=09/11/26&NumRooms=1#PageTop",
    "prideSeries": "GBP-associated / traveler-relevant, not an official GBP partnership"
  },
  {
    "id": "hospitality-hotel-habituel-3",
    "city": "Paris",
    "business": "Hôtel Habituel",
    "venueType": "Hotel",
    "uiCategory": "Where to Stay",
    "audienceTags": [
      "Queer-friendly"
    ],
    "description": "Official Global Black Pride host hotel offering convenient accommodations for attendees traveling to Paris for Pride week.",
    "venueName": "Hôtel Habituel",
    "venueAddress": "168 Rue Du Faubourg Saint Denis, Paris, 75010 France",
    "price": "$$$",
    "hasCommunityPerk": false,
    "code": "",
    "bookingLink": "https://globalblackpride.hotelplanner.com/Hotel/HotelRoomTypes.htm?hotelId=3181782&idTypeId=0&inDate=09/10/26&outDate=09/11/26&NumRooms=1#PageTop",
    "prideSeries": "GBP-associated / traveler-relevant, not an official GBP partnership"
  },
  {
    "id": "hospitality-hotel-josephine-spa-by-happyculture-4",
    "city": "Paris",
    "business": "Hôtel Joséphine & SPA by HappyCulture",
    "venueType": "Hotel",
    "uiCategory": "Where to Stay",
    "audienceTags": [
      "Queer-friendly"
    ],
    "description": "Boutique Paris hotel and spa near Moulin Rouge, with easy access to Pigalle nightlife, restaurants and public transportation.",
    "venueName": "Hôtel Joséphine & SPA by HappyCulture",
    "venueAddress": "67 Rue Blanche, 75009 Paris, France",
    "price": "$$",
    "hasCommunityPerk": false,
    "code": "",
    "bookingLink": "https://www.hotels.com/ho432666/hotel-josephine-by-happyculture-paris-france/?semcid=HCOM-US.UB.GOOGLE.PT-DSA-c-EN.HOTEL&semdtl=a113512932875.b1126438050351.g1aud-2187993911458:dsa-1315439953433.e1c.m1CjwKCAjwwfnUBhAtEiwAfQpAYsn7W36YtpEqIEr2deiyxlWINdSVWsjtAlIBMj1oHrGUMV8Wf8U8NhoCRasQAvD_BwE.r1.c1.j19007526.k1.d1660080613038.h1.i1285262490480.l1.n1.o1.p1.q1.s1.t1.x1.f1.u1.v1.w1&gad_source=1&gad_campaignid=13512932875&gbraid=0AAAAACTxZ9bIxfYzR99R6kX8TnJlLBNbH&gclid=CjwKCAjwwfnUBhAtEiwAfQpAYsn7W36YtpEqIEr2deiyxlWINdSVWsjtAlIBMj1oHrGUMV8Wf8U8NhoCRasQAvD_BwE",
    "prideSeries": "Independent"
  },
  {
    "id": "hospitality-bonjour-madame-5",
    "city": "Paris",
    "business": "Bonjour Madame",
    "venueType": "Bar, Restaurant",
    "uiCategory": "Where to Eat",
    "audienceTags": [
      "Queer",
      "Sapphic"
    ],
    "description": "Feminist, women-centered café-bar and queer-friendly gathering space for drinks, conversation and community.",
    "venueName": "Bonjour Madame",
    "venueAddress": "40 Rue de Montreuil, 75011 Paris, France",
    "price": "$$",
    "hasCommunityPerk": false,
    "code": "",
    "bookingLink": "https://www.instagram.com/bonjourmadame_paris/?hl=en",
    "prideSeries": "Independent"
  },
  {
    "id": "hospitality-la-mutinerie-6",
    "city": "Paris",
    "business": "La Mutinerie",
    "venueType": "Bar",
    "uiCategory": "Where to Drink",
    "audienceTags": [
      "Queer",
      "Sapphic"
    ],
    "description": "Queer feminist bar centering trans and lesbian communities, with community events, nightlife and an intentionally inclusive atmosphere.",
    "venueName": "La Mutinerie",
    "venueAddress": "176 Rue Saint Martin 75003 Paris",
    "price": "$",
    "hasCommunityPerk": false,
    "code": "",
    "bookingLink": "https://www.lamutinerie.eu/",
    "prideSeries": "Independent"
  },
  {
    "id": "hospitality-bar-les-aimant-7",
    "city": "",
    "business": "Bar les Aimant",
    "venueType": "Bar",
    "uiCategory": "Where to Drink",
    "audienceTags": [
      "Queer",
      "Sapphic"
    ],
    "description": "Queer-friendly Paris bar and gathering space for drinks, community and a casual night out.",
    "venueName": "Bar les Aimant",
    "venueAddress": "182 Rue Saint-Martin, 75003 Paris, France",
    "price": "$",
    "hasCommunityPerk": false,
    "code": "",
    "bookingLink": "https://www.instagram.com/barlesaimantes/?hl=en",
    "prideSeries": "Independent"
  },
  {
    "id": "hospitality-parc-des-buttes-chaumont-8",
    "city": "Paris",
    "business": "Rosa Bonheur",
    "venueType": "Bar",
    "uiCategory": "Where to Drink",
    "audienceTags": [
      "Queer",
      "Sapphic"
    ],
    "description": "Queer-friendly Paris bar and gathering space for drinks, community and a casual night out.",
    "venueName": "Parc des Buttes-Chaumont",
    "venueAddress": "2 allée de la Cascade, 75019 Paris",
    "price": "$$",
    "hasCommunityPerk": false,
    "code": "",
    "bookingLink": "https://www.instagram.com/popular/rosa-bonheur-paris/",
    "prideSeries": "Independent"
  },
  {
    "id": "hospitality-la-fleche-dor-9",
    "city": "Paris",
    "business": "La Fleche' dOr",
    "venueType": "Bar",
    "uiCategory": "Where to Drink",
    "audienceTags": [
      "Queer"
    ],
    "description": "Queer-friendly Paris bar and gathering space for drinks, community and a casual night out.",
    "venueName": "La Fleche' dOr",
    "venueAddress": "102 Bis Rue de Bagnolet, 75020 Paris, France",
    "price": "",
    "hasCommunityPerk": false,
    "code": "",
    "bookingLink": "https://flechedor.org/",
    "prideSeries": "Independent"
  },
  {
    "id": "hospitality-briquet-10",
    "city": "Paris",
    "business": "Briquet",
    "venueType": "Cafe, Non-alcoholi options",
    "uiCategory": "Where to Eat",
    "audienceTags": [
      "Queer-friendly",
      "Woman-owned"
    ],
    "description": "Coffee by day, natural wine by night. A relaxed, women-led spot featuring specialty coffee, non-alcoholic options and rotating guest chefs.",
    "venueName": "Briquet",
    "venueAddress": "7bis Rue Riquet, 75019 Paris, France",
    "price": "$$",
    "hasCommunityPerk": false,
    "code": "",
    "bookingLink": "https://www.instagram.com/briquet.paris/?hl=en",
    "prideSeries": "Independent"
  },
  {
    "id": "hospitality-dirty-lemon-11",
    "city": "Paris",
    "business": "Dirty Lemon",
    "venueType": "Cocktail Bar",
    "uiCategory": "Where to Drink",
    "audienceTags": [
      "Woman-owned",
      "WLW",
      "Lesbian",
      "Sapphic",
      "Nonbinary"
    ],
    "description": "Women-founded cocktail bar centering queer women and nonbinary folks, with creative drinks, mocktails and regular sapphic and community events.",
    "venueName": "Dirty Lemon",
    "venueAddress": "24 Rue de la Folie Méricourt, 75011 Paris, France",
    "price": "$$",
    "hasCommunityPerk": false,
    "code": "",
    "bookingLink": "https://www.dirtylemonbar.com/",
    "prideSeries": "Independent"
  },
  {
    "id": "hospitality-abricot-bar-12",
    "city": "Paris",
    "business": "Abricot Bar",
    "venueType": "Cocktail Bar",
    "uiCategory": "Where to Drink",
    "audienceTags": [
      "Queer-friendly",
      "Woman-owned"
    ],
    "description": "Women-owned cocktail bar with a relaxed, inclusive atmosphere, creative drinks and regular queer community gatherings.",
    "venueName": "Abricot Bar",
    "venueAddress": "189 Rue Saint-Maur, 75010 Paris, France",
    "price": "$$",
    "hasCommunityPerk": false,
    "code": "",
    "bookingLink": "https://www.abricotbar.com/",
    "prideSeries": "Independent"
  },
  {
    "id": "hospitality-sister-midnight-13",
    "city": "Paris",
    "business": "Sister Midnight",
    "venueType": "Cocktail Bar",
    "uiCategory": "Where to Drink",
    "audienceTags": [
      "Queer-friendly",
      "Woman-owned"
    ],
    "description": "Women-owned glam-rock cocktail bar known for its playful atmosphere, queer-friendly crowd and regular cabaret, burlesque and drag programming.",
    "venueName": "Sister Midnight",
    "venueAddress": "4 Rue Viollet-le-Duc, 75009 Paris, France",
    "price": "$$",
    "hasCommunityPerk": false,
    "code": "",
    "bookingLink": "https://www.sistermidnightparis.com/",
    "prideSeries": "Independent"
  },
  {
    "id": "hospitality-kuti-food-14",
    "city": "Paris",
    "business": "Kuti Food Restaurant Afro",
    "venueType": "Restaurant",
    "uiCategory": "Where to Eat",
    "audienceTags": [
      "Black-owned",
      "Queer-friendly"
    ],
    "description": "Casual Pan-African street food spot in Paris's 10th arrondissement serving bold flavors in a warm, vibrant and laid-back setting.",
    "venueName": "Kuti Food",
    "venueAddress": "6 Rue des Petites Écuries, 75010 Paris, France",
    "price": "$$",
    "hasCommunityPerk": false,
    "code": "",
    "bookingLink": "https://bookings.zenchef.com/results?rid=366535&pid=1001&isPreview=1",
    "prideSeries": "Independent"
  },
  {
    "id": "hospitality-jamrock-paris-15",
    "city": "Paris",
    "business": "Jamrock Paris",
    "venueType": "Restaurant",
    "uiCategory": "Where to Eat",
    "audienceTags": [
      "Black-owned",
      "Queer-friendly"
    ],
    "description": "Afro-Caribbean and Jamaican restaurant in the 11th arrondissement serving flavorful comfort food in a warm, casual and welcoming atmosphere.",
    "venueName": "Jamrock Paris",
    "venueAddress": "16 Rue de Candie, 75011 Paris, France",
    "price": "$$",
    "hasCommunityPerk": false,
    "code": "",
    "bookingLink": "https://jamrock-paris.com/en/booking",
    "prideSeries": "Independent"
  },
  {
    "id": "hospitality-bmk-paris-bamako-16",
    "city": "Paris",
    "business": "BMK Paris-Bamako",
    "venueType": "Restaurant",
    "uiCategory": "Where to Eat",
    "audienceTags": [
      "Black-owned",
      "Queer-friendly"
    ],
    "description": "West African-inspired restaurant in the 10th arrondissement serving flavorful dishes in a relaxed, modern setting.",
    "venueName": "BMK Paris-Bamako",
    "venueAddress": "14 Rue de la Fidélité, 75010 Paris, France",
    "price": "$$",
    "hasCommunityPerk": false,
    "code": "",
    "bookingLink": "https://www.bmkparis.com/reservez-votre-table-",
    "prideSeries": "Independent"
  },
  {
    "id": "hospitality-chop-chop-love-17",
    "city": "Paris",
    "business": "Chop Chop Love",
    "venueType": "Restaurant",
    "uiCategory": "Where to Eat",
    "audienceTags": [
      "POC",
      "Queer-friendly"
    ],
    "description": "Trendy natural wine bar and rotating culinary residency where guest chefs, creative food and Paris nightlife meet.",
    "venueName": "Chop Chop Love",
    "venueAddress": "48 Rue du Faubourg Saint-Martin, 75010 Paris, France",
    "price": "$$",
    "hasCommunityPerk": false,
    "code": "",
    "bookingLink": "https://bookings.zenchef.com/results?rid=376716&pid=1001&utm_source=ig&utm_medium=social&utm_content=link_in_bio&fbclid=PAcGRvZgJleHRuA2FlbQIxMQBzcnRjBmFwcF9pZA85MzY2MTk3NDMzOTI0NTkAAaeJ59Ze8JEEOvKxVZgDMUJn8eQU7XaZ9dZ_UHAexbkFLdbFrFyjb1nLezFN9g_aem_CaDC2IwucGYnx8QuRyL57Q",
    "prideSeries": "Independent"
  },
  {
    "id": "hospitality-la-charrette-a-crepes-18",
    "city": "Paris",
    "business": "La Charrette à Crêpes",
    "venueType": "Restaurant",
    "uiCategory": "Where to Eat",
    "audienceTags": [
      "Queer-friendly",
      "POC"
    ],
    "description": "Cozy Paris crêperie serving sweet and savory crêpes in a casual, welcoming setting near the heart of the Marais.",
    "venueName": "La Charrette à Crêpes",
    "venueAddress": "19 Rue Ferdinand Duval, 75004 Paris, France",
    "price": "$",
    "hasCommunityPerk": false,
    "code": "",
    "bookingLink": "https://www.lacharretteacrepes.fr/",
    "prideSeries": "Independent"
  },
  {
    "id": "hospitality-montvenus-19",
    "city": "Paris",
    "business": "Montvenus",
    "venueType": "Restaurant",
    "uiCategory": "Where to Eat",
    "audienceTags": [
      "Woman-owned",
      "Queer",
      "Sapphic"
    ],
    "description": "Queer and feminist cocktail bar blending drinks, arts, culture and community programming in an intentionally inclusive space.",
    "venueName": "Montvenus",
    "venueAddress": "16 Boulevard Paul Vaillant Couturier, 93100 Montreuil, France",
    "price": "$$",
    "hasCommunityPerk": false,
    "code": "",
    "bookingLink": "https://www.instagram.com/montvenus.montreuil/?hl=en",
    "prideSeries": "Independent"
  },
  {
    "id": "hospitality-le-barlone-20",
    "city": "Paris",
    "business": "Le Barlone",
    "venueType": "Restaurant",
    "uiCategory": "Where to Eat",
    "audienceTags": [
      "Woman-owned",
      "Queer-friendly"
    ],
    "description": "Queer-friendly lounge and cocktail bar pairing creative drinks with small plates in a stylish, intimate setting.",
    "venueName": "Le Barlone",
    "venueAddress": "13 Rue Bergère, 75009 Paris, France",
    "price": "$$",
    "hasCommunityPerk": false,
    "code": "",
    "bookingLink": "https://www.instagram.com/lebarlone/?hl=en",
    "prideSeries": "Independent"
  },
  {
    "id": "hospitality-babylone-bis-21",
    "city": "Paris",
    "business": "Babylone Bis",
    "venueType": "Restaurant",
    "uiCategory": "Where to Eat",
    "audienceTags": [
      "Black-owned",
      "Queer-friendly"
    ],
    "description": "Long-running late-night Paris restaurant known for its lively atmosphere, diverse crowd and West African and Caribbean flavors.",
    "venueName": "Babylone Bis",
    "venueAddress": "34 Rue Tiquetonne, 75002 Paris, France",
    "price": "$$",
    "hasCommunityPerk": false,
    "code": "",
    "bookingLink": "https://widget.thefork.com/en/5886f41b-f333-4e94-a41e-f5cf634b31ec?utm_source=ig&utm_medium=social&utm_content=link_in_bio&fbclid=PAcGRvZgJleHRuA2FlbQIxMQBzcnRjBmFwcF9pZA85MzY2MTk3NDMzOTI0NTkAAafHSXuTt5UOf3jbCi2HzovBWAVAS1EiBgcGVeZVq03K-_b4QGG1687UfNbyvA_aem_U-j3W4QQPO8PqrIUEqP36g&step=date",
    "prideSeries": "Independent"
  },
  {
    "id": "hospitality-gumbo-yaya-chicken-and-waffles-22",
    "city": "Paris",
    "business": "Gumbo Yaya Chicken and Waffles",
    "venueType": "Restaurant",
    "uiCategory": "Where to Eat",
    "audienceTags": [
      "Black-owned",
      "Queer-friendly"
    ],
    "description": "Black-owned chicken-and-waffles spot bringing Southern comfort food and bold flavors to Paris in a casual, energetic setting.",
    "venueName": "Gumbo Yaya Chicken and Waffles",
    "venueAddress": "3 Rue Charles Robin, 75010 Paris, France",
    "price": "$$",
    "hasCommunityPerk": false,
    "code": "",
    "bookingLink": "https://3615gumbo.com/?utm_source=ig&utm_medium=social&utm_content=link_in_bio&fbclid=PAcGRvZgJleHRuA2FlbQIxMQBzcnRjBmFwcF9pZA85MzY2MTk3NDMzOTI0NTkAAacMOZ6qLBK8LOh5yUsAnjtpbU_H_BidMli-ZKk2b89kzgdMg8WoqXaqOa9OnA_aem_sB0fFpBjMgObFUiGtXF8ow",
    "prideSeries": "Independent"
  },
  {
    "id": "hospitality-jah-jah-by-le-tricycle-23",
    "city": "Paris",
    "business": "Jah Jah by Le Tricycle",
    "venueType": "Restaurant",
    "uiCategory": "Where to Eat",
    "audienceTags": [
      "Black-owned",
      "Queer-friendly"
    ],
    "description": "Vegan Afro-Caribbean restaurant serving colorful, plant-based dishes in a relaxed space popular with Paris's creative and queer communities.",
    "venueName": "Jah Jah by Le Tricycle",
    "venueAddress": "11 Rue des Petites Écuries, 75010 Paris, France",
    "price": "$$",
    "hasCommunityPerk": false,
    "code": "",
    "bookingLink": "https://www.jahjahparis.com/",
    "prideSeries": "Independent"
  },
  {
    "id": "hospitality-a-l-africaine-24",
    "city": "Paris",
    "business": "A L'Africaine",
    "venueType": "Restaurant",
    "uiCategory": "Where to Eat",
    "audienceTags": [
      "Black-owned"
    ],
    "description": "Casual, family-style West African restaurant just outside central Paris, serving generous plates and comforting neighborhood flavors.",
    "venueName": "A L'Africaine",
    "venueAddress": "34 Rue Montcalm, 75018 Paris France",
    "price": "$$",
    "hasCommunityPerk": false,
    "code": "",
    "bookingLink": "https://www.lafricaine.fr/mobile/index.php?utm_source=ig&utm_medium=social&utm_content=link_in_bio&fbclid=PAcGRvZgJleHRuA2FlbQIxMQBzcnRjBmFwcF9pZA85MzY2MTk3NDMzOTI0NTkAAacPQBU_dEEnkKbGBXcVgqaZMpy4jeVBjdx0s3ina5BjZRhGmdFH5PIzm2AoLg_aem_EwRRIkG-6qVZo5790omP2A",
    "prideSeries": "Independent"
  },
  {
    "id": "hospitality-katoro-25",
    "city": "Paris",
    "business": "Katoro",
    "venueType": "Restaurant",
    "uiCategory": "Where to Eat",
    "audienceTags": [
      "Black-owned",
      "Queer-friendly"
    ],
    "description": "Warm neighborhood Caribbean restaurant in Paris's 13th arrondissement serving flavorful island-inspired dishes in a relaxed setting.",
    "venueName": "Katoro",
    "venueAddress": "85 Rue Albert, 75013 Paris, France",
    "price": "$$",
    "hasCommunityPerk": false,
    "code": "",
    "bookingLink": "https://www.instagram.com/ktoro_/?hl=en",
    "prideSeries": "Independent"
  },
  {
    "id": "hospitality-ose-african-26",
    "city": "Paris",
    "business": "Ose African",
    "venueType": "Restaurant",
    "uiCategory": "Where to Eat",
    "audienceTags": [
      "Black-owned"
    ],
    "description": "Casual African fast-good spot serving flavorful, modern takes on African cuisine in an easygoing Paris setting.",
    "venueName": "Ose African",
    "venueAddress": "14 Rue du Rocher, Paris, Ile-de-France 75008",
    "price": "$$",
    "hasCommunityPerk": false,
    "code": "",
    "bookingLink": "https://www.oseafricancuisine.com/",
    "prideSeries": "Independent"
  },
  {
    "id": "hospitality-gutea-27",
    "city": "Paris",
    "business": "GuTea",
    "venueType": "Restaurant",
    "uiCategory": "Where to Eat",
    "audienceTags": [
      "Queer-friendly",
      "POC"
    ],
    "description": "Creative bubble tea and activity spot where you can sip real-fruit drinks while painting your own figurine — part café, part playful Paris experience.",
    "venueName": "GuTea",
    "venueAddress": "1 Rue des Tanneries, 75013 Paris, France",
    "price": "$$",
    "hasCommunityPerk": false,
    "code": "",
    "bookingLink": "https://www.instagram.com/salon_gutea/?hl=en",
    "prideSeries": "Independent"
  },
  {
    "id": "hospitality-various-tour-based-28",
    "city": "Paris",
    "business": "Le Paris Noir",
    "venueType": "Tour, Educational",
    "uiCategory": "Experiences",
    "audienceTags": [
      "Black-owned",
      "Queer-friendly",
      "Black"
    ],
    "description": "Explore Black Paris through history, culture and storytelling, including a special James Baldwin-centered experience examining his life as a Black gay writer in Paris and the city's wider African and Caribbean presence.",
    "venueName": "Various / tour-based",
    "venueAddress": "Varies by experience",
    "price": "$$$",
    "hasCommunityPerk": true,
    "code": "Identify themselves as part of The Mahogany Pages when booking their tour.",
    "bookingLink": "https://www.tripadvisor.com/Attraction_Review-g187147-d4440931-Reviews-Le_Paris_Noir_Tours_Prives-Paris_Ile_de_France.html",
    "prideSeries": "Independent"
  },
  {
    "id": "hospitality-hotel-national-des-arts-et-metiers-29",
    "city": "Paris",
    "business": "Gay Paris Noir: A Black Queer Culture Walk",
    "venueType": "Tour, Educational",
    "uiCategory": "Experiences",
    "audienceTags": [
      "Black",
      "Queer",
      "Sapphic",
      "Black-owned"
    ],
    "description": "Guided cultural walk through Black queer Paris, tracing overlooked icons, artists and activists from the 1920s to today, with stories of James Baldwin, Josephine Baker, queer nightlife and contemporary community.",
    "venueName": "Hôtel National des Arts et Métiers",
    "venueAddress": "243 Rue Saint-Martin, 75003 Paris*",
    "price": "$",
    "hasCommunityPerk": true,
    "code": "Identify themselves as part of The Mahogany Pages when booking their tour.",
    "bookingLink": "https://www.airbnb.com/experiences/974110",
    "prideSeries": "Independent"
  },
  {
    "id": "hospitality-various-tour-based-30",
    "city": "Paris",
    "business": "Entrée to Black Paris",
    "venueType": "Tour, Educational",
    "uiCategory": "Experiences",
    "audienceTags": [
      "Black",
      "Queer-friendly",
      "Black-owned"
    ],
    "description": "Discover Black Paris through guided experiences exploring the city's rich Black history, culture and contemporary life.",
    "venueName": "Various / tour-based",
    "venueAddress": "Varies by experience",
    "price": "$$",
    "hasCommunityPerk": false,
    "code": "",
    "bookingLink": "https://www.entreetoblackparis.com/",
    "prideSeries": "Independent"
  },
  {
    "id": "hospitality-the-norm-agency-31",
    "city": "Paris",
    "business": "The Norm Agency",
    "venueType": "Museum/Gallery/Exhibits",
    "uiCategory": "Experiences",
    "audienceTags": [
      "Black",
      "POC",
      "Queer",
      "MLM",
      "Sapphic",
      "Trans",
      "GNC"
    ],
    "description": "International queer arts agency behind QADS, bringing together queer art, design, culture and creative collaborations across cities.",
    "venueName": "The Norm Agency",
    "venueAddress": "35 Rue Blanche, 75009 Paris, France",
    "price": "$",
    "hasCommunityPerk": false,
    "code": "",
    "bookingLink": "https://www.instagram.com/thenorm_art/?hl=en",
    "prideSeries": "Independent"
  },
  {
    "id": "hospitality-in-the-footsteps-of-josephine-baker-32",
    "city": "Paris",
    "business": "Musee Josephine Baker",
    "venueType": "Museum/Gallery/Exhibits",
    "uiCategory": "Experiences",
    "audienceTags": [
      "Black",
      "Queer",
      "Sapphic"
    ],
    "description": "A mobile and pop-up cultural experience dedicated to preserving Josephine Baker's legacy through walking tours, exhibits and programming connected to her life in Paris.",
    "venueName": "In the Footsteps of Josephine Baker",
    "venueAddress": "Reach out to founder directly via the Musée Joséphine Baker et des Afro-Descendants de Paris Instagram",
    "price": "$",
    "hasCommunityPerk": false,
    "code": "",
    "bookingLink": "https://www.airbnb.com/experiences/1120070?--&c=.pi0.pk22658761899_182381801642&gad_source=1&gad_campaignid=22658761899&gbraid=0AAAAADz55LkzWiJR-O_D7eVxMNBNdFKSI&gclid=Cj0KCQjw5P7UBhDaARIsAOSlS1Pe7IOqlXO4erwzmuSREk2MH0zZbtoakuOlRM8hGLgnXsyLcuFV4i4aAmmEEALw_wcB",
    "prideSeries": "Independent"
  },
  {
    "id": "hospitality-place-andre-honnorat-75006-paris-33",
    "city": "Paris",
    "business": "The Fête de Paris",
    "venueType": "Festival , Outdoors Hangout",
    "uiCategory": "Experiences",
    "audienceTags": [
      "Queer-friendly"
    ],
    "description": "A celebration of Paris, its history and its culture.",
    "venueName": "Place André Honnorat, 75006 Paris",
    "venueAddress": "Place André Honnorat, 75006 Paris, France",
    "price": "$",
    "hasCommunityPerk": false,
    "code": "",
    "bookingLink": "https://lafetedeparis.fr/",
    "prideSeries": "Independent"
  },
  {
    "id": "hospitality-reunion-market-34",
    "city": "Paris",
    "business": "Griot Festival: 30 years of culture in Paris's 20th arrondissement",
    "venueType": "Festival , Outdoors Hangout",
    "uiCategory": "Experiences",
    "audienceTags": [
      "Black"
    ],
    "description": "A lively, intergenerational celebration of West African music, dance, traditions and culture in Paris's 20th arrondissement, presented by Benkadi Afema 20.",
    "venueName": "Réunion Market",
    "venueAddress": "Place de la Réunion, Paris 20th",
    "price": "$",
    "hasCommunityPerk": false,
    "code": "",
    "bookingLink": "https://lafetedeparis.fr/",
    "prideSeries": "Independent"
  },
  {
    "id": "hospitality-cabaret-des-merveilles-35",
    "city": "Paris",
    "business": "Cabaret des Merveilles",
    "venueType": "Nightclub, Bar",
    "uiCategory": "Where to Dance",
    "audienceTags": [
      "POC",
      "Sapphic",
      "WLW",
      "Lesbian"
    ],
    "description": "Queer and lesbian-centered cabaret and arts space creating a home for feminist and FLINTA communities, performances and nightlife.",
    "venueName": "Cabaret des Merveilles",
    "venueAddress": "25 Rue de l'Hirondelle, 75006 Paris, France",
    "price": "$$",
    "hasCommunityPerk": false,
    "code": "",
    "bookingLink": "https://www.instagram.com/cabaret_des_merveilles/",
    "prideSeries": "Independent"
  },
  {
    "id": "hospitality-various-pop-up-based-36",
    "city": "Paris",
    "business": "Le Pulse",
    "venueType": "Nightclub",
    "uiCategory": "Where to Dance",
    "audienceTags": [
      "Black",
      "Sapphic",
      "Queer",
      "POC",
      "FLINTA",
      "Trans",
      "GNC",
      "WLW",
      "Lesbian",
      "Nonbinary"
    ],
    "description": "Paris-based lesbian and FLINTA party collective known for inclusive club nights, DJ sets, pop-ups and a strong safer-space ethos.",
    "venueName": "Various / pop-up based",
    "venueAddress": "Various / pop-up based",
    "price": "$",
    "hasCommunityPerk": false,
    "code": "",
    "bookingLink": "https://www.instagram.com/pulseparis/?hl=en",
    "prideSeries": "Independent"
  },
  {
    "id": "hospitality-le-bunker-37",
    "city": "Paris",
    "business": "Le Bunker",
    "venueType": "Nightclub",
    "uiCategory": "Where to Dance",
    "audienceTags": [
      "Black",
      "Sapphic",
      "Queer",
      "Black-owned",
      "WLW",
      "Lesbian"
    ],
    "description": "Black and POC-centered queer nightlife space bringing Afrobeat, dancehall, shatta and community energy to Paris.",
    "venueName": "Le Bunker",
    "venueAddress": "54 Rue Guy Môquet, 75017 Paris",
    "price": "$$",
    "hasCommunityPerk": false,
    "code": "",
    "bookingLink": "https://www.instagram.com/lebunkerparis/",
    "prideSeries": "Independent"
  },
  {
    "id": "hospitality-le-raidd-38",
    "city": "Paris",
    "business": "Le Raidd",
    "venueType": "Bar",
    "uiCategory": "Where to Drink",
    "audienceTags": [
      "Black",
      "MLM",
      "Queer"
    ],
    "description": "Iconic Paris gay nightlife destination known for its high-energy crowd, late nights and signature shower performances.",
    "venueName": "Le Raidd",
    "venueAddress": "23 Rue du Temple in the heart of Le Marais",
    "price": "$$",
    "hasCommunityPerk": false,
    "code": "",
    "bookingLink": "https://www.raiddbar.com/",
    "prideSeries": "Independent"
  },
  {
    "id": "hospitality-troupe-venus-noire-39",
    "city": "Paris",
    "business": "Troupe Venus Noire",
    "venueType": "Bar",
    "uiCategory": "Where to Drink",
    "audienceTags": [
      "Black",
      "Queer",
      "MLM"
    ],
    "description": "Black queer cabaret collective bringing immersive performance, dance, music and theatrical nightlife to the stage.",
    "venueName": "Troupe Venus Noire",
    "venueAddress": "25 rue de l'Hirondelle in Paris's 6th arrondissement",
    "price": "$",
    "hasCommunityPerk": false,
    "code": "",
    "bookingLink": "https://www.instagram.com/venus___noire/?hl=en",
    "prideSeries": "Independent"
  },
  {
    "id": "hospitality-billetterie-rex-club-pari-40",
    "city": "Paris",
    "business": "Billetterie – Rex Club Pari",
    "venueType": "Nightclub",
    "uiCategory": "Where to Dance",
    "audienceTags": [
      "Black",
      "MLM",
      "Queer",
      "Sapphic"
    ],
    "description": "Legendary Paris electronic music club known for late-night techno, house and an energetic dance floor that runs into the early morning.",
    "venueName": "Billetterie – Rex Club Pari",
    "venueAddress": "5 Boulevard Poissonnière, 75002 Paris, France",
    "price": "$",
    "hasCommunityPerk": false,
    "code": "",
    "bookingLink": "https://shotgun.live/fr/venues/rex-club",
    "prideSeries": "Independent"
  },
  {
    "id": "hospitality-afro-queer-rising-41",
    "city": "Paris",
    "business": "Afro Queer Rising",
    "venueType": "Bar",
    "uiCategory": "Where to Drink",
    "audienceTags": [
      "Black",
      "MLM",
      "Queer"
    ],
    "description": "Black queer artist and performance collective blending African and Afro-diasporic culture with cabaret, music, dance and late-night club energy.",
    "venueName": "Afro Queer Rising",
    "venueAddress": "Various / pop-up based",
    "price": "$",
    "hasCommunityPerk": false,
    "code": "",
    "bookingLink": "https://www.instagram.com/afroqueerrising/?hl=en",
    "prideSeries": "Independent"
  },
  {
    "id": "hospitality-blatino-club-paris-gay-42",
    "city": "Paris",
    "business": "Blatino Club Paris Gay",
    "venueType": "Nightclub",
    "uiCategory": "Where to Dance",
    "audienceTags": [
      "Black",
      "MLM",
      "Queer"
    ],
    "description": "Recurring Black and Latino LGBTQ+ nightlife experience centering multicultural queer men and friends through music, dancing and community.",
    "venueName": "Blatino Club Paris Gay",
    "venueAddress": "Various / pop-up based",
    "price": "$",
    "hasCommunityPerk": false,
    "code": "",
    "bookingLink": "https://www.instagram.com/blatinoclubparis/",
    "prideSeries": "Independent"
  },
  {
    "id": "hospitality-afro-boyz-club-43",
    "city": "Paris",
    "business": "Afro Boyz Club",
    "venueType": "Nightclub",
    "uiCategory": "Where to Dance",
    "audienceTags": [
      "Black",
      "MLM",
      "Queer"
    ],
    "description": "Afro-Caribbean LGBTQ+ party collective bringing high-energy Black queer nightlife, DJs and dance-floor energy to Paris.",
    "venueName": "Afro Boyz Club",
    "venueAddress": "Various / pop-up based",
    "price": "$",
    "hasCommunityPerk": false,
    "code": "",
    "bookingLink": "https://www.instagram.com/afroboyzclub/?hl=en",
    "prideSeries": "Independent"
  },
  {
    "id": "hospitality-queer-salsa-paris-44",
    "city": "Paris",
    "business": "Queer Salsa Paris",
    "venueType": "Nightclub",
    "uiCategory": "Where to Dance",
    "audienceTags": [
      "Black",
      "MLM",
      "Queer"
    ],
    "description": "LGBTQIA+ salsa, bachata and kizomba collective creating inclusive, gender-neutral social dance experiences in Paris.",
    "venueName": "Queer Salsa Paris",
    "venueAddress": "Various / pop-up based",
    "price": "$",
    "hasCommunityPerk": false,
    "code": "",
    "bookingLink": "https://www.instagram.com/queersalsaparis/",
    "prideSeries": "Independent"
  },
  {
    "id": "hospitality-cud-bar-paris-45",
    "city": "Paris",
    "business": "CUD Bar Paris",
    "venueType": "Nightclub",
    "uiCategory": "Where to Dance",
    "audienceTags": [
      "Black",
      "MLM",
      "Queer"
    ],
    "description": "Late-night gay bar and basement dance club in the Marais, known for its lively after-hours crowd and dancing until dawn.",
    "venueName": "CUD Bar Paris",
    "venueAddress": "12 Rue des Haudriettes, 75003 Paris, France",
    "price": "$$",
    "hasCommunityPerk": false,
    "code": "",
    "bookingLink": "https://cudbar.com/",
    "prideSeries": "Independent"
  },
  {
    "id": "hospitality-quetzal-bar-paris-46",
    "city": "Paris",
    "business": "Quetzal Bar Paris",
    "venueType": "Nightclub",
    "uiCategory": "Where to Dance",
    "audienceTags": [
      "Black",
      "MLM",
      "Queer",
      "30+"
    ],
    "description": "Lively gay bar in the Marais with DJs, drinks and a social, high-energy atmosphere that gets especially busy on weekends.",
    "venueName": "Quetzal Bar Paris",
    "venueAddress": "10 Rue de la Verrerie, 75004 Paris, France",
    "price": "$$",
    "hasCommunityPerk": false,
    "code": "",
    "bookingLink": "https://www.instagram.com/quetzalparis/?hl=en",
    "prideSeries": "Independent"
  },
  {
    "id": "hospitality-bienvenue-freedj-bar-47",
    "city": "Paris",
    "business": "Bienvenue Freedj Bar",
    "venueType": "Nightclub",
    "uiCategory": "Where to Dance",
    "audienceTags": [
      "Black",
      "MLM",
      "Queer"
    ],
    "description": "Two-level gay bar and club in the heart of the Marais, with an upstairs lounge and basement dance floor playing pop and house.",
    "venueName": "Bienvenue Freedj Bar",
    "venueAddress": "35 Rue Sainte-Croix de la Bretonnerie, 75004 Paris, France",
    "price": "$$",
    "hasCommunityPerk": false,
    "code": "",
    "bookingLink": "https://freedj.fr/",
    "prideSeries": "Independent"
  },
  {
    "id": "hospitality-bears-den-paris-48",
    "city": "Paris",
    "business": "Bears'den Paris",
    "venueType": "Nightclub",
    "uiCategory": "Where to Dance",
    "audienceTags": [
      "Black",
      "MLM",
      "Queer"
    ],
    "description": "Long-running gay bear bar near the Marais with a lively terrace, indoor bar and downstairs dance floor and social space.",
    "venueName": "Bears'den Paris",
    "venueAddress": "6 Rue des Lombards, 75004 Paris, France",
    "price": "$$",
    "hasCommunityPerk": false,
    "code": "",
    "bookingLink": "https://www.instagram.com/bearsden_bearbar_paris/?hl=en",
    "prideSeries": "Independent"
  },
  {
    "id": "hospitality-le-47-par-romeo-49",
    "city": "Paris",
    "business": "Le 47 par Romeo",
    "venueType": "Cocktail Bar, Restaurant",
    "uiCategory": "Where to Drink",
    "audienceTags": [
      "Queer-friendly"
    ],
    "description": "Upscale restaurant and cocktail bar inside Hôtel Château Frontenac, offering a chic, intimate setting in Paris's Golden Triangle.",
    "venueName": "Le 47 par Romeo",
    "venueAddress": "47 Rue François 1er, 75008 Paris, France",
    "price": "$$$",
    "hasCommunityPerk": false,
    "code": "",
    "bookingLink": "https://www.hfrontenac.com/en/collection/restaurant-le-47.1870.html",
    "prideSeries": "Independent"
  },
  {
    "id": "hospitality-causier-coffee-50",
    "city": "Paris",
    "business": "Causier Coffee",
    "venueType": "Cafe",
    "uiCategory": "Where to Eat",
    "audienceTags": [
      "Queer-friendly"
    ],
    "description": "Cozy neighborhood café in the 11th arrondissement serving coffee, lunch and brunch in a warm, laid-back setting.",
    "venueName": "Causier Coffee",
    "venueAddress": "50 Rue de Montreuil, 75011 Paris, France",
    "price": "$$",
    "hasCommunityPerk": false,
    "code": "",
    "bookingLink": "https://www.causier.fr/",
    "prideSeries": "Independent"
  },
  {
    "id": "hospitality-sister-midnight-51",
    "city": "Paris",
    "business": "Drag King Daisy Lusion at Sister Midnight",
    "venueType": "Cocktail Bar",
    "uiCategory": "Where to Dance",
    "audienceTags": [
      "Drag",
      "POC",
      "Queer"
    ],
    "description": "Tiny Pigalle cocktail bar that comes alive on Saturday nights with drag and burlesque performances from local and visiting artists, all wrapped in Sister Midnight's signature glam-rock energy.",
    "venueName": "Sister Midnight",
    "venueAddress": "4 Rue Viollet-le-Duc, 75009 Paris, France",
    "price": "$",
    "hasCommunityPerk": false,
    "code": "",
    "bookingLink": "https://www.instagram.com/sistermidnightparis/?hl=en",
    "prideSeries": "Independent"
  },
  {
    "id": "hospitality-oh-cesar-palace-52",
    "city": "Paris",
    "business": "Oh! César Palace",
    "venueType": "Live Show, Restaurant, Cocktail Bar",
    "uiCategory": "Experiences",
    "audienceTags": [
      "POC",
      "Queer-friendly"
    ],
    "description": "Dinner, show and nightlife all in one: enjoy a lively meal alongside performances from dancers, comedians, aerial acrobats, musicians and magicians, then keep the night going with cocktails and dancing until 1:45 AM.",
    "venueName": "Oh! César Palace",
    "venueAddress": "23 Av. du Maine, 75015 Paris",
    "price": "$$",
    "hasCommunityPerk": true,
    "code": "",
    "bookingLink": "https://ohcesarparis.com/brian-scott-bagley/",
    "prideSeries": "Independent"
  }
];
